# scripts/report_accuracy.py
"""
Measured accuracy against independently generated ground truth.

WHY THIS EXISTS SEPARATELY FROM THE GOLD BASELINE
--------------------------------------------------
`verify_e2e_gold_baseline.py` answers "is the engine still producing
what it produced before?" -- reproducibility. It runs each case in
isolation, which means it structurally cannot evaluate ambiguity or
duplicate detection, and reports those six cases as NOT_EVALUABLE.

This script answers a different question: "how often is the engine
RIGHT?" It runs the full batch in one pass -- the way the pipeline
actually runs -- so batch-relational properties are observable, and
compares every decision against ground_truth.json.

Both numbers are worth having. Neither substitutes for the other.

WHAT IT COMPARES
----------------
    ground_truth.json          expected_status, expected_exception_code
    decide_batch() output      status, exception_code

Ground truth is generated by scripts/generate_data.py alongside the
data itself and is NEVER read by the pipeline. The reconciliation
engine has no access to it, so this is an independent comparison
rather than the system grading its own homework.

TWO SEPARATE ACCURACY FIGURES
-----------------------------
Status accuracy and exception-code accuracy are reported separately
because they can diverge and the difference is diagnostic. A record
with the right status and the wrong code means the engine reached the
correct operational outcome by a route the ground truth did not
predict -- worth knowing, and not the same failure as getting the
outcome wrong.

RECORDS NOT PRESENT IN THE OUTPUT
---------------------------------
Corrupted records are rejected at ingestion and never produce a
MatchDecision. Ground truth has 63 entries; decide_batch() returns 61.
Those two are counted explicitly as `rejected_at_ingestion` rather
than silently dropped from the denominator -- dropping them would
quietly inflate the percentage.

THE LABEL-CORRECTION DISCLOSURE
-------------------------------
Two ground-truth labels were corrected after the engine disagreed with
them (FAILURE_LOG.md sections 14-15). That history is printed with the
result rather than left for a reviewer to discover, because "we
changed the answer key" is a fair thing to ask about and a better
thing to volunteer.

Run:
    python scripts/report_accuracy.py
"""

from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent.parent))

from src.ingestion.loader import load_batch
from src.normalization.engine import normalize_batch
from src.matching.engine import run_matching
from src.exceptions.manager import decide_batch


ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = ROOT / "data" / "raw"
GT_PATH = ROOT / "data" / "ground_truth.json"
OUTPUT_PATH = ROOT / "data" / "eval" / "accuracy_report.json"

RULE = "=" * 72


# Ground-truth labels corrected after the engine disagreed with them.
# Disclosed in the output rather than left to be found.
LABEL_CORRECTIONS = [
    {
        "category": "duplicate",
        "was": "AMBIGUOUS",
        "now": "HUMAN_REVIEW",
        "reason": (
            "decision_table maps duplicate_detected to HUMAN_REVIEW at "
            "priority 1 and never produced AMBIGUOUS. A duplicate is "
            "one transaction appearing twice; ambiguity is two "
            "different transactions competing. Different operational "
            "responses."
        ),
        "log_ref": "FAILURE_LOG.md section 14 (L1)",
    },
    {
        "category": "unresolvable",
        "was": "UNMATCHED / HUMAN_REVIEW_REQUIRED",
        "now": "HUMAN_REVIEW / AMOUNT_MISMATCH",
        "reason": (
            "UNMATCHED requires no_candidates_found -- both bank and "
            "invoice absent. The builder emits all three sources and "
            "keeps bank_ref resolvable, so a counterpart IS found and "
            "the INR 50 shortfall is correctly an amount mismatch."
        ),
        "log_ref": "FAILURE_LOG.md section 15 (L2)",
    },
]


def load_ground_truth() -> dict[str, dict]:
    with GT_PATH.open("r", encoding="utf-8") as handle:
        return {entry["txn_id"]: entry for entry in json.load(handle)}


def run_pipeline():
    """
    Full batch in one pass, exactly as the pipeline runs in production.

    Not per-case. Ambiguity and duplicate detection depend on other
    records existing in the same batch; evaluating them one at a time
    makes them structurally undetectable.
    """
    batch = load_batch(RAW_DIR)
    normalized = normalize_batch(batch)
    return decide_batch(run_matching(normalized.records))


def main() -> None:
    ground_truth = load_ground_truth()
    decisions = run_pipeline()
    by_txn = {d.txn_id: d for d in decisions}

    print()
    print(RULE)
    print("MEASURED ACCURACY vs INDEPENDENT GROUND TRUTH")
    print(RULE)
    print()
    print("Full-batch execution. Ground truth is generated alongside")
    print("the data and never read by the pipeline.")
    print()

    status_correct = 0
    code_correct = 0
    evaluated = 0

    rejected_at_ingestion = []
    divergences = []

    per_category = defaultdict(
        lambda: {"total": 0, "status_ok": 0, "code_ok": 0}
    )

    for txn_id, expected in sorted(ground_truth.items()):
        category = expected["category"]
        per_category[category]["total"] += 1

        decision = by_txn.get(txn_id)

        if decision is None:
            # Corrupted records never reach decisioning. Counted, not
            # dropped -- dropping would inflate the percentage.
            rejected_at_ingestion.append({
                "txn_id": txn_id,
                "category": category,
                "expected_status": expected["expected_status"],
            })
            continue

        evaluated += 1

        actual_status = decision.status.value
        actual_code = decision.exception_code.value

        status_ok = actual_status == expected["expected_status"]
        code_ok = actual_code == expected["expected_exception_code"]

        if status_ok:
            status_correct += 1
            per_category[category]["status_ok"] += 1
        if code_ok:
            code_correct += 1
            per_category[category]["code_ok"] += 1

        if not (status_ok and code_ok):
            divergences.append({
                "txn_id": txn_id,
                "category": category,
                "expected_status": expected["expected_status"],
                "actual_status": actual_status,
                "expected_exception_code": expected[
                    "expected_exception_code"
                ],
                "actual_exception_code": actual_code,
                "status_matched": status_ok,
                "code_matched": code_ok,
                "reason_codes": [
                    c.value for c in decision.reason_codes
                ],
            })

    # ------------------------------------------------------------------
    # HEADLINE
    # ------------------------------------------------------------------

    status_pct = (
        round(100.0 * status_correct / evaluated, 2) if evaluated else 0.0
    )
    code_pct = (
        round(100.0 * code_correct / evaluated, 2) if evaluated else 0.0
    )

    print(f"  Ground-truth entries       : {len(ground_truth)}")
    print(f"  Rejected at ingestion      : "
          f"{len(rejected_at_ingestion)} (corrupted, never decisioned)")
    print(f"  Decisions evaluated        : {evaluated}")
    print()
    print(f"  STATUS accuracy            : "
          f"{status_correct}/{evaluated}  ({status_pct}%)")
    print(f"  EXCEPTION-CODE accuracy    : "
          f"{code_correct}/{evaluated}  ({code_pct}%)")
    print()

    # ------------------------------------------------------------------
    # PER CATEGORY
    # ------------------------------------------------------------------

    print(RULE)
    print("BY CATEGORY")
    print(RULE)
    print()
    header = f"  {'category':<28}{'status':<12}{'code':<12}"
    print(header)
    print("  " + "-" * (len(header) - 2))

    for category in sorted(per_category):
        stats = per_category[category]
        decided = stats["total"] - sum(
            1 for r in rejected_at_ingestion
            if r["category"] == category
        )

        if decided == 0:
            print(f"  {category:<28}{'n/a':<12}{'n/a':<12}"
                  f"(rejected at ingestion)")
            continue

        print(
            f"  {category:<28}"
            f"{stats['status_ok']}/{decided:<10}"
            f"{stats['code_ok']}/{decided:<10}"
        )

    print()

    # ------------------------------------------------------------------
    # DIVERGENCES
    # ------------------------------------------------------------------

    print(RULE)
    print(f"DIVERGENCES ({len(divergences)})")
    print(RULE)
    print()

    if not divergences:
        print("  None. Every decision matched ground truth on both")
        print("  status and exception code.")
    else:
        for item in divergences:
            print(f"  {item['txn_id']} ({item['category']})")
            if not item["status_matched"]:
                print(f"    status : expected "
                      f"{item['expected_status']}, got "
                      f"{item['actual_status']}")
            if not item["code_matched"]:
                print(f"    code   : expected "
                      f"{item['expected_exception_code']}, got "
                      f"{item['actual_exception_code']}")
            print(f"    reason codes: {item['reason_codes']}")
            print()

    print()

    # ------------------------------------------------------------------
    # DISCLOSURE
    # ------------------------------------------------------------------

    print(RULE)
    print("GROUND-TRUTH LABEL CORRECTIONS")
    print(RULE)
    print()
    print("  Two labels were corrected after the engine disagreed with")
    print("  them. Disclosed here rather than left to be discovered.")
    print()

    for correction in LABEL_CORRECTIONS:
        print(f"  {correction['category']}: "
              f"{correction['was']} -> {correction['now']}")
        print(f"    {correction['reason']}")
        print(f"    {correction['log_ref']}")
        print()

    print("  The decision table is the specification. It was written")
    print("  first and is exhaustively tested over all 512 boolean")
    print("  combinations. Both labels described statuses no rule in")
    print("  that table produces, so the labels were wrong about the")
    print("  spec -- not the engine wrong about reality.")
    print()

    # ------------------------------------------------------------------
    # SCOPE
    # ------------------------------------------------------------------

    print(RULE)
    print("SCOPE")
    print(RULE)
    print()
    print("  Self-generated dataset. This measures the engine against")
    print("  the failure modes this generator produces. It does not")
    print("  establish generalisation to real bank data -- see the")
    print("  limitations section of README.md.")
    print()

    # ------------------------------------------------------------------
    # ARTIFACT
    # ------------------------------------------------------------------

    report = {
        "report_version": "accuracy-v1",
        "method": (
            "Full-batch execution compared against ground_truth.json, "
            "which is generated alongside the data and never read by "
            "the pipeline."
        ),
        "ground_truth_entries": len(ground_truth),
        "rejected_at_ingestion": len(rejected_at_ingestion),
        "decisions_evaluated": evaluated,
        "status_accuracy": {
            "correct": status_correct,
            "total": evaluated,
            "percent": status_pct,
        },
        "exception_code_accuracy": {
            "correct": code_correct,
            "total": evaluated,
            "percent": code_pct,
        },
        "by_category": {
            category: dict(stats)
            for category, stats in sorted(per_category.items())
        },
        "divergences": divergences,
        "rejected_records": rejected_at_ingestion,
        "ground_truth_label_corrections": LABEL_CORRECTIONS,
        "scope": (
            "Self-generated dataset. Measures the engine against the "
            "failure modes this generator produces; does not establish "
            "generalisation to real bank data."
        ),
    }

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=2, ensure_ascii=False)

    print(f"  Artifact: {OUTPUT_PATH}")
    print()


if __name__ == "__main__":
    main()